# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\muham\OneDrive\Desktop\PyqtFinal\untitled5.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Ui_untitled import BirinciSayfa
from Ui_untitled2 import İkinciSayfa
from Ui_untitled3 import UcuncuSayfa
from Ui_untitled4 import DorduncuSayfa

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Choice Screen")
        MainWindow.resize(249, 229)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bookDetails_btn = QtWidgets.QPushButton(self.centralwidget)
        self.bookDetails_btn.setGeometry(QtCore.QRect(130, 10, 91, 71))
        self.bookDetails_btn.setObjectName("bookDetails_btn")
        self.bookDetails_btn.clicked.connect(self.bookDetails_btn_clicked)
        self.books_btn = QtWidgets.QPushButton(self.centralwidget)
        self.books_btn.setGeometry(QtCore.QRect(20, 10, 91, 71))
        self.books_btn.setObjectName("books_btn")
        self.books_btn.clicked.connect(self.books_btn_clicked)
        self.order_btn = QtWidgets.QPushButton(self.centralwidget)
        self.order_btn.setGeometry(QtCore.QRect(20, 100, 91, 71))
        self.order_btn.setObjectName("order_btn")
        self.order_btn.clicked.connect(self.order_btn_clicked)
        self.sale_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sale_btn.setGeometry(QtCore.QRect(130, 100, 91, 71))
        self.sale_btn.setObjectName("sale_btn")
        self.sale_btn.clicked.connect(self.sale_btn_clicked)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 249, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Choice Screen", "Choice Screen"))
        self.bookDetails_btn.setText(_translate("MainWindow", "Book Details"))
        self.books_btn.setText(_translate("MainWindow", "Books"))
        self.order_btn.setText(_translate("MainWindow", "Order"))
        self.sale_btn.setText(_translate("MainWindow", "Sale"))

    def books_btn_clicked(self,MainWindow):
        self.openBooks = OpenBooks()
        self.openBooks.show()  

    def bookDetails_btn_clicked(self,MainWindow):
        self.openBooksDetails = OpenBookDetails()
        self.openBooksDetails.show()  

    def order_btn_clicked(self,MainWindow):
        self.openOrder = OpenBooks()
        self.openOrder.show()  

    def sale_btn_clicked(self,MainWindow):
        self.openSale = OpenSale()
        self.openSale.show()  

class OpenBooks(QtWidgets.QMainWindow):
    def __init__(self):
        super(OpenBooks, self).__init__()
        self.openBooks = BirinciSayfa()
        self.openBooks.setupUi(self) 



class OpenBookDetails(QtWidgets.QMainWindow):
    def __init__(self):
        super(OpenBookDetails, self).__init__()
        self.openBooksDetails = İkinciSayfa()
        self.openBooksDetails.setupUi(self) 



class OpenOrder(QtWidgets.QMainWindow):
    def __init__(self):
        super(OpenOrder, self).__init__()
        self.openOrder = UcuncuSayfa()
        self.openOrder.setupUi(self) 



class OpenSale(QtWidgets.QMainWindow):
    def __init__(self):
        super(OpenSale, self).__init__()
        self.openBooks = DorduncuSayfa()
        self.openBooks.setupUi(self) 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())